package uaic.fii.protobuf;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: publication.proto

import com.google.protobuf.AbstractMessageLite;

public final class PublicationOuterClass {
  private PublicationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PublicationFieldOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PublicationField)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string value = 2;</code>
     * @return The value.
     */
    String getValue();
    /**
     * <code>string value = 2;</code>
     * @return The bytes for value.
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code PublicationField}
   */
  public static final class PublicationField extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PublicationField)
      PublicationFieldOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PublicationField.newBuilder() to construct.
    private PublicationField(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PublicationField() {
      name_ = "";
      value_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new PublicationField();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PublicationOuterClass.internal_static_PublicationField_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PublicationOuterClass.internal_static_PublicationField_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PublicationField.class, Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @Override
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile Object value_ = "";
    /**
     * <code>string value = 2;</code>
     * @return The value.
     */
    @Override
    public String getValue() {
      Object ref = value_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>string value = 2;</code>
     * @return The bytes for value.
     */
    @Override
    public com.google.protobuf.ByteString
        getValueBytes() {
      Object ref = value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(value_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, value_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(value_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PublicationField)) {
        return super.equals(obj);
      }
      PublicationField other = (PublicationField) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getValue()
          .equals(other.getValue())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PublicationField parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PublicationField parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PublicationField parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PublicationField parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PublicationField parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PublicationField parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PublicationField parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PublicationField parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static PublicationField parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static PublicationField parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PublicationField parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PublicationField parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PublicationField prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PublicationField}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PublicationField)
        PublicationFieldOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PublicationOuterClass.internal_static_PublicationField_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PublicationOuterClass.internal_static_PublicationField_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PublicationField.class, Builder.class);
      }

      // Construct using PublicationOuterClass.PublicationField.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        name_ = "";
        value_ = "";
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PublicationOuterClass.internal_static_PublicationField_descriptor;
      }

      @Override
      public PublicationField getDefaultInstanceForType() {
        return PublicationField.getDefaultInstance();
      }

      @Override
      public PublicationField build() {
        PublicationField result = buildPartial();
        if (!result.isInitialized()) {
          throw Builder.newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public PublicationField buildPartial() {
        PublicationField result = new PublicationField(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(PublicationField result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.value_ = value_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PublicationField) {
          return mergeFrom((PublicationField)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PublicationField other) {
        if (other == PublicationField.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                value_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        AbstractMessageLite.checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private Object value_ = "";
      /**
       * <code>string value = 2;</code>
       * @return The value.
       */
      public String getValue() {
        Object ref = value_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string value = 2;</code>
       * @return The bytes for value.
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string value = 2;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        value_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string value = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        value_ = getDefaultInstance().getValue();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string value = 2;</code>
       * @param value The bytes for value to set.
       * @return This builder for chaining.
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        AbstractMessageLite.checkByteStringIsUtf8(value);
        value_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PublicationField)
    }

    // @@protoc_insertion_point(class_scope:PublicationField)
    private static final PublicationField DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PublicationField();
    }

    public static PublicationField getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PublicationField>
        PARSER = new com.google.protobuf.AbstractParser<PublicationField>() {
      @Override
      public PublicationField parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PublicationField> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<PublicationField> getParserForType() {
      return PARSER;
    }

    @Override
    public PublicationField getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PublicationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Publication)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .PublicationField publicationFieldList = 1;</code>
     */
    java.util.List<PublicationField>
        getPublicationFieldListList();
    /**
     * <code>repeated .PublicationField publicationFieldList = 1;</code>
     */
    PublicationField getPublicationFieldList(int index);
    /**
     * <code>repeated .PublicationField publicationFieldList = 1;</code>
     */
    int getPublicationFieldListCount();
    /**
     * <code>repeated .PublicationField publicationFieldList = 1;</code>
     */
    java.util.List<? extends PublicationFieldOrBuilder>
        getPublicationFieldListOrBuilderList();
    /**
     * <code>repeated .PublicationField publicationFieldList = 1;</code>
     */
    PublicationFieldOrBuilder getPublicationFieldListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Publication}
   */
  public static final class Publication extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Publication)
      PublicationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Publication.newBuilder() to construct.
    private Publication(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Publication() {
      publicationFieldList_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Publication();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PublicationOuterClass.internal_static_Publication_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PublicationOuterClass.internal_static_Publication_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Publication.class, Builder.class);
    }

    public static final int PUBLICATIONFIELDLIST_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<PublicationField> publicationFieldList_;
    /**
     * <code>repeated .PublicationField publicationFieldList = 1;</code>
     */
    @Override
    public java.util.List<PublicationField> getPublicationFieldListList() {
      return publicationFieldList_;
    }
    /**
     * <code>repeated .PublicationField publicationFieldList = 1;</code>
     */
    @Override
    public java.util.List<? extends PublicationFieldOrBuilder>
        getPublicationFieldListOrBuilderList() {
      return publicationFieldList_;
    }
    /**
     * <code>repeated .PublicationField publicationFieldList = 1;</code>
     */
    @Override
    public int getPublicationFieldListCount() {
      return publicationFieldList_.size();
    }
    /**
     * <code>repeated .PublicationField publicationFieldList = 1;</code>
     */
    @Override
    public PublicationField getPublicationFieldList(int index) {
      return publicationFieldList_.get(index);
    }
    /**
     * <code>repeated .PublicationField publicationFieldList = 1;</code>
     */
    @Override
    public PublicationFieldOrBuilder getPublicationFieldListOrBuilder(
        int index) {
      return publicationFieldList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < publicationFieldList_.size(); i++) {
        output.writeMessage(1, publicationFieldList_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < publicationFieldList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, publicationFieldList_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Publication)) {
        return super.equals(obj);
      }
      Publication other = (Publication) obj;

      if (!getPublicationFieldListList()
          .equals(other.getPublicationFieldListList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPublicationFieldListCount() > 0) {
        hash = (37 * hash) + PUBLICATIONFIELDLIST_FIELD_NUMBER;
        hash = (53 * hash) + getPublicationFieldListList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Publication parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Publication parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Publication parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Publication parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Publication parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Publication parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Publication parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Publication parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Publication parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Publication parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Publication parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Publication parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Publication prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Publication}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Publication)
        PublicationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PublicationOuterClass.internal_static_Publication_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PublicationOuterClass.internal_static_Publication_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Publication.class, Builder.class);
      }

      // Construct using PublicationOuterClass.Publication.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (publicationFieldListBuilder_ == null) {
          publicationFieldList_ = java.util.Collections.emptyList();
        } else {
          publicationFieldList_ = null;
          publicationFieldListBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PublicationOuterClass.internal_static_Publication_descriptor;
      }

      @Override
      public Publication getDefaultInstanceForType() {
        return Publication.getDefaultInstance();
      }

      @Override
      public Publication build() {
        Publication result = buildPartial();
        if (!result.isInitialized()) {
          throw Builder.newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Publication buildPartial() {
        Publication result = new Publication(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(Publication result) {
        if (publicationFieldListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            publicationFieldList_ = java.util.Collections.unmodifiableList(publicationFieldList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.publicationFieldList_ = publicationFieldList_;
        } else {
          result.publicationFieldList_ = publicationFieldListBuilder_.build();
        }
      }

      private void buildPartial0(Publication result) {
        int from_bitField0_ = bitField0_;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Publication) {
          return mergeFrom((Publication)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Publication other) {
        if (other == Publication.getDefaultInstance()) return this;
        if (publicationFieldListBuilder_ == null) {
          if (!other.publicationFieldList_.isEmpty()) {
            if (publicationFieldList_.isEmpty()) {
              publicationFieldList_ = other.publicationFieldList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePublicationFieldListIsMutable();
              publicationFieldList_.addAll(other.publicationFieldList_);
            }
            onChanged();
          }
        } else {
          if (!other.publicationFieldList_.isEmpty()) {
            if (publicationFieldListBuilder_.isEmpty()) {
              publicationFieldListBuilder_.dispose();
              publicationFieldListBuilder_ = null;
              publicationFieldList_ = other.publicationFieldList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              publicationFieldListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPublicationFieldListFieldBuilder() : null;
            } else {
              publicationFieldListBuilder_.addAllMessages(other.publicationFieldList_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                PublicationField m =
                    input.readMessage(
                        PublicationField.parser(),
                        extensionRegistry);
                if (publicationFieldListBuilder_ == null) {
                  ensurePublicationFieldListIsMutable();
                  publicationFieldList_.add(m);
                } else {
                  publicationFieldListBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<PublicationField> publicationFieldList_ =
        java.util.Collections.emptyList();
      private void ensurePublicationFieldListIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          publicationFieldList_ = new java.util.ArrayList<PublicationField>(publicationFieldList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          PublicationField, PublicationField.Builder, PublicationFieldOrBuilder> publicationFieldListBuilder_;

      /**
       * <code>repeated .PublicationField publicationFieldList = 1;</code>
       */
      public java.util.List<PublicationField> getPublicationFieldListList() {
        if (publicationFieldListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(publicationFieldList_);
        } else {
          return publicationFieldListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .PublicationField publicationFieldList = 1;</code>
       */
      public int getPublicationFieldListCount() {
        if (publicationFieldListBuilder_ == null) {
          return publicationFieldList_.size();
        } else {
          return publicationFieldListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .PublicationField publicationFieldList = 1;</code>
       */
      public PublicationField getPublicationFieldList(int index) {
        if (publicationFieldListBuilder_ == null) {
          return publicationFieldList_.get(index);
        } else {
          return publicationFieldListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .PublicationField publicationFieldList = 1;</code>
       */
      public Builder setPublicationFieldList(
          int index, PublicationField value) {
        if (publicationFieldListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePublicationFieldListIsMutable();
          publicationFieldList_.set(index, value);
          onChanged();
        } else {
          publicationFieldListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PublicationField publicationFieldList = 1;</code>
       */
      public Builder setPublicationFieldList(
          int index, PublicationField.Builder builderForValue) {
        if (publicationFieldListBuilder_ == null) {
          ensurePublicationFieldListIsMutable();
          publicationFieldList_.set(index, builderForValue.build());
          onChanged();
        } else {
          publicationFieldListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PublicationField publicationFieldList = 1;</code>
       */
      public Builder addPublicationFieldList(PublicationField value) {
        if (publicationFieldListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePublicationFieldListIsMutable();
          publicationFieldList_.add(value);
          onChanged();
        } else {
          publicationFieldListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .PublicationField publicationFieldList = 1;</code>
       */
      public Builder addPublicationFieldList(
          int index, PublicationField value) {
        if (publicationFieldListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePublicationFieldListIsMutable();
          publicationFieldList_.add(index, value);
          onChanged();
        } else {
          publicationFieldListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PublicationField publicationFieldList = 1;</code>
       */
      public Builder addPublicationFieldList(
          PublicationField.Builder builderForValue) {
        if (publicationFieldListBuilder_ == null) {
          ensurePublicationFieldListIsMutable();
          publicationFieldList_.add(builderForValue.build());
          onChanged();
        } else {
          publicationFieldListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PublicationField publicationFieldList = 1;</code>
       */
      public Builder addPublicationFieldList(
          int index, PublicationField.Builder builderForValue) {
        if (publicationFieldListBuilder_ == null) {
          ensurePublicationFieldListIsMutable();
          publicationFieldList_.add(index, builderForValue.build());
          onChanged();
        } else {
          publicationFieldListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PublicationField publicationFieldList = 1;</code>
       */
      public Builder addAllPublicationFieldList(
          Iterable<? extends PublicationField> values) {
        if (publicationFieldListBuilder_ == null) {
          ensurePublicationFieldListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, publicationFieldList_);
          onChanged();
        } else {
          publicationFieldListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .PublicationField publicationFieldList = 1;</code>
       */
      public Builder clearPublicationFieldList() {
        if (publicationFieldListBuilder_ == null) {
          publicationFieldList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          publicationFieldListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .PublicationField publicationFieldList = 1;</code>
       */
      public Builder removePublicationFieldList(int index) {
        if (publicationFieldListBuilder_ == null) {
          ensurePublicationFieldListIsMutable();
          publicationFieldList_.remove(index);
          onChanged();
        } else {
          publicationFieldListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .PublicationField publicationFieldList = 1;</code>
       */
      public PublicationField.Builder getPublicationFieldListBuilder(
          int index) {
        return getPublicationFieldListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .PublicationField publicationFieldList = 1;</code>
       */
      public PublicationFieldOrBuilder getPublicationFieldListOrBuilder(
          int index) {
        if (publicationFieldListBuilder_ == null) {
          return publicationFieldList_.get(index);  } else {
          return publicationFieldListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .PublicationField publicationFieldList = 1;</code>
       */
      public java.util.List<? extends PublicationFieldOrBuilder>
           getPublicationFieldListOrBuilderList() {
        if (publicationFieldListBuilder_ != null) {
          return publicationFieldListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(publicationFieldList_);
        }
      }
      /**
       * <code>repeated .PublicationField publicationFieldList = 1;</code>
       */
      public PublicationField.Builder addPublicationFieldListBuilder() {
        return getPublicationFieldListFieldBuilder().addBuilder(
            PublicationField.getDefaultInstance());
      }
      /**
       * <code>repeated .PublicationField publicationFieldList = 1;</code>
       */
      public PublicationField.Builder addPublicationFieldListBuilder(
          int index) {
        return getPublicationFieldListFieldBuilder().addBuilder(
            index, PublicationField.getDefaultInstance());
      }
      /**
       * <code>repeated .PublicationField publicationFieldList = 1;</code>
       */
      public java.util.List<PublicationField.Builder>
           getPublicationFieldListBuilderList() {
        return getPublicationFieldListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          PublicationField, PublicationField.Builder, PublicationFieldOrBuilder>
          getPublicationFieldListFieldBuilder() {
        if (publicationFieldListBuilder_ == null) {
          publicationFieldListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              PublicationField, PublicationField.Builder, PublicationFieldOrBuilder>(
                  publicationFieldList_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          publicationFieldList_ = null;
        }
        return publicationFieldListBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Publication)
    }

    // @@protoc_insertion_point(class_scope:Publication)
    private static final Publication DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Publication();
    }

    public static Publication getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Publication>
        PARSER = new com.google.protobuf.AbstractParser<Publication>() {
      @Override
      public Publication parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Publication> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Publication> getParserForType() {
      return PARSER;
    }

    @Override
    public Publication getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PublicationField_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PublicationField_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Publication_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Publication_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021publication.proto\"/\n\020PublicationField\022" +
      "\014\n\004name\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\">\n\013Publicat" +
      "ion\022/\n\024publicationFieldList\030\001 \003(\0132\021.Publ" +
      "icationFieldb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PublicationField_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PublicationField_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PublicationField_descriptor,
        new String[] { "Name", "Value", });
    internal_static_Publication_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Publication_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Publication_descriptor,
        new String[] { "PublicationFieldList", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
